name: my-first-workflow
#To get trigger on every push in this repo in any branch
on: push

jobs:
   job1:
      name: JOB1
      runs-on: ubuntu-latest
      steps:
         - name: Running Single Command in Job1
           run: echo "Hi, this is my first GitHub workflow"        
         - name: Checking OS release for GitHub Workflow
           run: [ -f /etc/os-release ] && cat /etc/os-release
