name: my-first-workflow
#To get trigger on every push in this repo in any branch
on: push

jobs:
   job1:
      name: JOB1
      runs-on: ubuntu-latest
      steps:
         - name: Running Single Command in Job1
           run: echo "Hi, this is my first GitHub workflow"        
         - name: Checking OS release for GitHub Workflow
           run: cat /etc/os-release
         - name: Calling Sleep
           run: sleep 25
   job2:
      name: JOB2
      runs-on: ubuntu-latest
      steps:
         - name: Checking the Hostname for Runner
           run: hostname     
         - name: Running Multiple Commands
           run: |
              echo "hi from Andre Kueda"
              echo "current time is 'date'"
              sleep 20
   job3:
      name: JOB3
      needs: job1
      runs-on: ubuntu-latest
      steps:
         - name: Job with Single Dependency
           run: sleep 10
   job4:
      name: JOB4
      needs: [job1, job2, job3]
      runs-on: ubuntu-latest
      steps:
         - name: Job With Multiple dependecies
           run: sleep 15
